version: "3"

services:
  # # php
  web_service:
    image: "bitnami/symfony:1"
    ports:
      - "8000:8000"
    depends_on:
      - rabbitmq
      - mysql8
    volumes:
      - ".:/app/myapp"

  # mysql
  mysql8:
    image: mysql:8
    ports:
      - "4306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always # always restart unless stopped manually
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_PASSWORD: secret

  # # node
  # node-service:
  #   image: node:latest
  #   container_name: node-container
  #   volumes:
  #     - ./app:/var/www/project
  #   working_dir: /var/www/project
  #   networks:
  #     - newParserServiceNetwork

  #rabbitmq
  rabbitmq:
    image: rabbitmq:3.8-management
    ports: [5672, 15672]
